### ISSUE TITLE
Enklu Market is extremely slow

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/indexer#322]
The graphql queries originating from the enklu market are extremely slow.

**Comment by kespinola** [comment]
<img width="558" alt="Screen Shot 2022-03-30 at 12 16 52 PM" src="https://user-images.githubusercontent.com/2388118/160913429-1504a2b0-9615-44df-b2d5-ce47de3c4735.png">
I thinking its with these invalid creators.

**Comment by kespinola** [comment]
https://bafkreiep6izhzcxrais7gpvzyf2n47j3k664kdueojnwxe275kqqwk67a4.ipfs.dweb.link/?ext=

This is occurring because the query to find the first 3 nfts for the collection is scanning the whole db because these aren't the correct creator address (ie not first verified creator).

They removed the creators but reindexing with the removal code not out yet. I'm correcting by hand since the json is correct just not our index.

**Comment by ray-kast** [comment]
@kespinola is this resolved?

**Comment by dandlezzz** [comment]
resolved.
