### ISSUE TITLE
allow filtering feedEvents query by event types

### ISSUE THREAD

**Issue by austinmilt** [holaplex/indexer#485]
To facilitate surfacing only the events that are relevant - e.g. on holaplex.com not showing follow events, we should add an optional parameter to the `feedEvents` query to filter returned events by type (e.g. mint, follow, purchase, etc).

**Comment by austinmilt** [comment]
@kespinola I see what you meant about needing to convert the query to sea-query to allow for conditional joins. I started down that path, but (a) didnt finish, and (b) dont really understand what's required (based on looking at `metadata.rs`).

I think for purposes of the homepage v2 we can leave the query as-is until I have time to dig in more, and at that point we can do some pair programming. Unless you want to tackle it yourself.

WIP branch https://github.com/holaplex/indexer/compare/austin/485/feed-events-filters?expand=1

**Comment by austinmilt** [comment]
cc @kristianeboe

**Comment by kespinola** [comment]
I know we discussed include list but after thinking though the code I'm switch boats to exclude list.

The API can be:

```graphql
feedEvents(wallet: "", exclude_types: ["FOLLOW"], limit: 20, offset: 0) {
  ... MintEvent {
  }
  ... ListingEvent {
  }
}
```

The argument should be Option<Vec<String>> if omitted then all events should be returned. It be great to represent the event_type as a scalar but can look into that later eventType: [EventType]


```rust
let mut query = ...
if let Some(excluded_types) = excluded_types {
  for event_type in  event_types {
      query = match event_type {
        "FOLLOW" => {
          query.filter(follow_events::graph_connection.is_not_null())
          _ => {
             query
          }
        }
     }
}
```

This will execute the and_then when exclude_types is some. The closure loops through each event and adds filter to exclude  that event type from the results. I think this can be improved by keeping a hash of the transforms instead of a match clause but

**Comment by austinmilt** [comment]
@kespinola so you think it's fine to go ahead and join all tables, but then filter out stuff we dont want (as opposed to only joining to tables we want)?

**Comment by austinmilt** [comment]
Working off a new branch https://github.com/holaplex/indexer/compare/austin/homepage-v2-various?expand=1
