### ISSUE TITLE
Migrate Staging Rabbit to Kubernetes

### ISSUE THREAD

**Issue by kespinola** [holaplex/indexer#837]
### Goal
Move staging rabbitMQ for indexer over to Kubernetes with same specs as the current production instance.

**Comment by mpwsh** [comment]
A 3 node RabbitMQ cluster has been deployed on `stage-indexer` & `devnet-indexer` namespaces using the rabbitMQ [cluster operator](https://github.com/rabbitmq/cluster-operator) and migrated both successfully on Friday.

NAT usage for both staging and devnet indexers has lowered to 0 because we are now exposing Rabbit through a network load balancer, which is only using 3GB when receiving startup messages.  

Management and monitoring:
- [Grafana dashboard](https://graf.holaplex.tools/d/Kn5xm-gZk/rabbitmq-overview?orgId=1&var-DS_PROMETHEUS=prometheus&var-namespace=stage-indexer&var-rabbitmq_cluster=rabbitmq&from=now-6h&to=now)
- [Admin Console UI Staging](mq-stage.mainnet.holaplex.tools/)
- [Admin Console UI Devnet](mq.devnet.holaplex.tools/)

**Comment by kespinola** [comment]
done.
